variables:
  sdkVersion: '3.1.x'
  buildConfiguration: 'Release'
  tests: 'test/**/*.csproj'

jobs:
  - job: Test
    displayName: 'Build and Test'
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      # Install
      - task: UseDotNet@2
        displayName: 'Installing .Net Core SDK'
        inputs:
          version: $(sdkVersion)
      # Restore
      - task: DotNetCoreCLI@2
        displayName: 'Restore packages'
        inputs:
          command: restore
          projects: '**/*.csproj'
      # Build
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)'
      # Test
      - task: DotNetCoreCLI@2
        inputs:
          command: test
          projects: '$(tests)'
          arguments: '--configuration $(buildConfiguration)'
